-- File: and_gate.vhd
-- Generated by MyHDL 0.6
-- Date: Fri Nov  5 19:12:03 2010

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_06.all;

entity and_gate is
    port (
        op1: in unsigned(0 downto 0);
        op2: in unsigned(0 downto 0);
        out: out unsigned(0 downto 0)
    );
end entity and_gate;

architecture MyHDL of and_gate is


begin



out <= (op1 and op2);

end architecture MyHDL;
