-- File: control.vhd
-- Generated by MyHDL 0.6
-- Date: Tue Nov  2 12:18:24 2010

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_06.all;

entity control is
    port (
        opcode: in unsigned(5 downto 0);
        RegDst: out unsigned(0 downto 0);
        Branch: out unsigned(0 downto 0);
        MemRead: out unsigned(0 downto 0);
        MemtoReg: out unsigned(0 downto 0);
        ALUop: out unsigned(1 downto 0);
        MemWrite: out unsigned(0 downto 0);
        ALUSrc: out unsigned(0 downto 0);
        RegWrite: out unsigned(0 downto 0)
    );
end entity control;

architecture MyHDL of control is


begin


CONTROL_LOGIC: process (opcode) is
begin
    if (opcode = 0) then
        RegDst <= "1";
        ALUSrc <= "0";
        MemtoReg <= "0";
        RegWrite <= "1";
        MemRead <= "0";
        MemWrite <= "0";
        Branch <= "0";
        ALUop <= to_unsigned(string'("10"), 2);
    elsif (opcode = 35) then
        RegDst <= "0";
        ALUSrc <= "1";
        MemtoReg <= "1";
        RegWrite <= "1";
        MemRead <= "1";
        MemWrite <= "0";
        Branch <= "0";
        ALUop <= to_unsigned(string'("00"), 2);
    elsif (opcode = 43) then
        ALUSrc <= "1";
        RegWrite <= "0";
        MemRead <= "0";
        MemWrite <= "1";
        Branch <= "0";
        ALUop <= to_unsigned(string'("00"), 2);
    elsif (opcode = 4) then
        ALUSrc <= "0";
        RegWrite <= "0";
        MemRead <= "0";
        MemWrite <= "0";
        Branch <= "1";
        ALUop <= to_unsigned(string'("01"), 2);
    end if;
end process CONTROL_LOGIC;

end architecture MyHDL;
