-- File: hazard_detector.vhd
-- Generated by MyHDL 0.6
-- Date: Fri Nov 19 11:17:56 2010

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_06.all;

entity hazard_detector is
    port (
        MemRead_ex: in unsigned(0 downto 0);
        Rt_ex: in unsigned(4 downto 0);
        Rs_id: in unsigned(4 downto 0);
        Rt_id: in unsigned(4 downto 0);
        Stall: out unsigned(0 downto 0)
    );
end entity hazard_detector;

architecture MyHDL of hazard_detector is


begin


HAZARD_DETECTOR_LOGIC: process (Rt_id, Rs_id, Rt_ex, MemRead_ex) is
begin
    if ((MemRead_ex = 1) and ((Rt_ex = Rs_id) or (Rt_ex = Rt_id))) then
        Stall <= "1";
    else
        Stall <= "0";
    end if;
end process HAZARD_DETECTOR_LOGIC;

end architecture MyHDL;
