-- File: latch_if_id.vhd
-- Generated by MyHDL 0.6
-- Date: Fri Nov 19 13:51:30 2010

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_06.all;

entity latch_if_id is
    port (
        clk: in unsigned(0 downto 0);
        rst: in unsigned(0 downto 0);
        instruction_in: in unsigned(31 downto 0);
        pc_adder_in: in unsigned(31 downto 0);
        instruction_out: out unsigned(31 downto 0);
        pc_adder_out: out unsigned(31 downto 0);
        stall: in unsigned(0 downto 0)
    );
end entity latch_if_id;

architecture MyHDL of latch_if_id is


begin


LATCH_IF_ID_LATCH: process (clk, rst) is
begin
    if (rst = 1) then
        instruction_out <= "00000000000000000000000000000000";
        pc_adder_out <= "00000000000000000000000000000000";
    elsif rising_edge(clk) then
        if (not to_boolean(stall)) then
            instruction_out <= instruction_in;
            pc_adder_out <= pc_adder_in;
        end if;
    end if;
end process LATCH_IF_ID_LATCH;

end architecture MyHDL;
