-- File: latch_mem_wb.vhd
-- Generated by MyHDL 0.6
-- Date: Sat Nov 13 12:00:52 2010

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_06.all;

entity latch_mem_wb is
    port (
        clk: in unsigned(0 downto 0);
        rst: in unsigned(0 downto 0);
        ram_in: in signed (31 downto 0);
        alu_result_in: in signed (31 downto 0);
        wr_reg_in: in signed (31 downto 0);
        RegWrite_in: in unsigned(0 downto 0);
        MemtoReg_in: in unsigned(0 downto 0);
        ram_out: out signed (31 downto 0);
        alu_result_out: out signed (31 downto 0);
        wr_reg_out: out signed (31 downto 0);
        RegWrite_out: out unsigned(0 downto 0);
        MemtoReg_out: out unsigned(0 downto 0)
    );
end entity latch_mem_wb;

architecture MyHDL of latch_mem_wb is


begin


LATCH_MEM_WB_LATCH: process (clk, rst) is
begin
    if (rst = 1) then
        ram_out <= "00000000000000000000000000000000";
        alu_result_out <= "00000000000000000000000000000000";
        wr_reg_out <= "00000000000000000000000000000000";
        RegWrite_out <= "0";
        MemtoReg_out <= "0";
    elsif rising_edge(clk) then
        ram_out <= ram_in;
        alu_result_out <= alu_result_in;
        wr_reg_out <= wr_reg_in;
        RegWrite_out <= RegWrite_in;
        MemtoReg_out <= MemtoReg_in;
    end if;
end process LATCH_MEM_WB_LATCH;

end architecture MyHDL;
