-- File: mux4.vhd
-- Generated by MyHDL 0.6
-- Date: Sat Nov 20 01:30:08 2010

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_06.all;

entity mux4 is
    port (
        sel: in unsigned(1 downto 0);
        mux_out: out unsigned(31 downto 0);
        chan1: in unsigned(31 downto 0);
        chan2: in unsigned(31 downto 0);
        chan3: in unsigned(31 downto 0);
        chan4: in unsigned(31 downto 0)
    );
end entity mux4;

architecture MyHDL of mux4 is


begin


MUX4_ROUTE_CHANNEL: process (chan4, sel, chan1, chan3, chan2) is
begin
    if (sel = 0) then
        mux_out <= chan1;
    elsif (sel = 1) then
        mux_out <= chan2;
    elsif (sel = 2) then
        mux_out <= chan3;
    elsif (sel = 3) then
        mux_out <= chan4;
    end if;
end process MUX4_ROUTE_CHANNEL;

end architecture MyHDL;
