-- File: program_counter.vhd
-- Generated by MyHDL 0.6
-- Date: Sun Oct 31 23:25:32 2010

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_06.all;

entity program_counter is
    port (
        clk: in unsigned(0 downto 0);
        address: inout unsigned(4 downto 0)
    );
end entity program_counter;

architecture MyHDL of program_counter is


begin


PROGRAM_COUNTER_INC: process (clk) is
begin
    if rising_edge(clk) then
        address <= (address + 1);
    end if;
end process PROGRAM_COUNTER_INC;

end architecture MyHDL;
