-- File: sign_extend.vhd
-- Generated by MyHDL 0.6
-- Date: Thu Oct 28 20:04:13 2010

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_06.all;

entity sign_extend is
    port (
        input16: in signed (15 downto 0);
        output32: out signed (31 downto 0)
    );
end entity sign_extend;

architecture MyHDL of sign_extend is


begin



output32 <= resize(input16, 32);

end architecture MyHDL;
